// apps/web-astro/src/components/ColorOnVisible.tsx
import * as React from 'react';

export type ColorOnVisibleProps = React.PropsWithChildren<{}>;

const ColorOnVisible: React.FC<ColorOnVisibleProps> = ({ children }) => {
  const refContainer = React.useRef<HTMLDivElement>(null);
  const [color, setColor] = React.useState('red');

  React.useEffect(() => {
    const element = refContainer.current;

    if (!element) {
      return;
    }

    const observer = new IntersectionObserver((entries) => {
      if (entries[0].isIntersecting) {
        setColor('blue');
      }
    });

    observer.observe(element);
  }, []);

  return (
    <section
      ref={refContainer}
      style={
        {
          background: 'var(--color)',
          padding: '4rem',
          transition: 'background-color 0.6s ease-out',
          '--color': color,
        } as React.CSSProperties
      }
    >
      {children}
    </section>
  );
};

export default ColorOnVisible;

// apps/web-qwik/src/components/ColorOnVisible.tsx
import { Slot, component$, useSignal, useVisibleTask$ } from '@builder.io/qwik';

const ColorOnVisible = component$(() => {
  const containerSignal = useSignal<HTMLDivElement>();
  const colorSignal = useSignal('red');

  useVisibleTask$(
    () => {
      const element = containerSignal.value;

      if (!element) {
        return;
      }

      const observer = new IntersectionObserver((entries) => {
        if (entries[0].isIntersecting) {
          colorSignal.value = 'blue';
        }
      });

      observer.observe(element);
    },
    { strategy: 'intersection-observer' }
  );

  return (
    <section
      ref={containerSignal}
      style={{
        background: 'var(--color)',
        padding: '4rem',
        transition: 'background-color 0.6s ease-out',
        '--color': colorSignal.value,
      }}
    >
      <Slot />
    </section>
  );
});

export default ColorOnVisible;
