// apps/web-qwik/src/components/Counter.tsx
import { component$, useSignal } from '@builder.io/qwik';

export type CounterProps = {
  defaultValue: number;
};

export const Counter = component$<CounterProps>((props) => {
  const valueSignal = useSignal(props.defaultValue);

  return (
    <div>
      <p>Value: {valueSignal.value}</p>
      <div>
        <button
          preventdefault:click
          onClick$={() => {
            valueSignal.value++;
          }}
        >
          +
        </button>
        <button
          preventdefault:click
          onClick$={() => {
            valueSignal.value--;
          }}
        >
          -
        </button>
      </div>
    </div>
  );
});

// apps/web-nextjs/components/Counter.tsx
'use client';

import React from 'react';

export type CounterProps = {
  defaultValue: number;
};

const Counter: React.FC<CounterProps> = ({ defaultValue }) => {
  const [value, setValue] = React.useState(defaultValue);

  return (
    <div>
      <p>Value: {value}</p>
      <div>
        <button
          onClick={(event) => {
            event.preventDefault();
            setValue(value + 1);
          }}
        >
          +
        </button>
        <button
          onClick={(event) => {
            event.preventDefault();
            setValue(value - 1);
          }}
        >
          -
        </button>
      </div>
    </div>
  );
};

export default Counter;
