// apps/web-qwik/src/routes/large/index.tsx
import { component$ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import ColorOnVisible from '~/components/ColorOnVisible';

export default component$(() => {
  return (
    <div>
      {Array.from(Array(1000)).map((_, index) => (
        <ColorOnVisible key={index}>Item {index}</ColorOnVisible>
      ))}
    </div>
  );
});

export const head: DocumentHead = {
  title: 'Qwik - Large Page',
};

// apps/web-nextjs/app/large/page.tsx
import { Metadata } from 'next';
import ColorOnVisible from '../../components/ColorOnVisible';

export default function CounterPage() {
  return (
    <div>
      {Array.from(Array(1000)).map((_, index) => (
        <ColorOnVisible key={index}>Item {index}</ColorOnVisible>
      ))}
    </div>
  );
}

export const metadata: Metadata = {
  title: 'Next.js - Large Page',
};
